network={
        ssid="eduroam"
        key_mgmt=WPA-EAP
        pairwise=CCMP
        group=CCMP
        eap=PEAP
        ca_cert="/home/codespace/.config/cat_installer/ca.pem"
        identity="te26718@qmul.ac.uk"
        altsubject_match="DNS:radius2.qmul.ac.uk"
        phase2="auth=MSCHAPV2"
	password="Gandhi's-s4lt"
	anonymous_identity="te26718@qmul.ac.uk"

}